version: "3.7"
volumes:
  adt2fhir_data:

services:
  adt2fhir:
    image: docker.verbis.dkfz.de/ccp/adt2fhir:test
    #image: adt2fhir
    #build this image locally using the Dockerfile "docker build -t adt2fhir ."
    environment:
      FILE_PATH: "/adt2fhir/clinical_data"
      STORE_PATH: "http://host.docker.internal:8090/fhir"
      IDENTIFIER_SYSTEM: "http://dktk.dkfz.de/fhir/onco/core/CodeSystem/PseudonymArtCS"
      MAINZELLIST_URL: "http://host.docker.internal:8080"
      MAINZELLIST_APIKEY: "pleaseChangeMe"
    volumes:
      - ./clinical_data:/adt2fhir/clinical_data
    #in case you run a separate docker-compose.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"